import Head from "next/head";
import { Box } from "@chakra-ui/react";
import PlayerList from "Players/features/PlayerList";
import PageLayout from "Base/layout/PageLayout";
import { useRouter } from "next/router";
import { useCallback } from "react";
import PlayersHeader from "Players/components/PlayersHeader";

export default function Home() {
  const router = useRouter();

  const navigateToCreatePlayer = useCallback(
    () => router.push("/player/create"),
    [router]
  );

  return (
    <>
      <Head>
        <title>Liga de Padel Baradero | Jugadores</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Box as="main" p={4}>
        <PageLayout>
          {{
            header: (
              <PlayersHeader navigateToCreatePlayer={navigateToCreatePlayer} />
            ),
            content: <PlayerList />,
          }}
        </PageLayout>
      </Box>
    </>
  );
}
