import { useCallback } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Box } from "@chakra-ui/react";

import PageLayout from "Base/layout/PageLayout";
import TournamentsHeader from "Tournaments/components/PlayersHeader";
import TournamentList from "Tournaments/features/TournamentList";

// import TournamentList from "Tournaments/features/TournamentList";
// import TournamentsHeader from "Tournaments/components/TournamentsHeader";

export default function Home() {
  const router = useRouter();

  const navigateToCreateTournament = useCallback(
    () => router.push("/tournament/create"),
    [router]
  );

  const navigateToTournamentDetails = useCallback(
    (tournamentId: string) => {
      router.push(`/tournaments/${tournamentId}`);
    },
    [router]
  );

  return (
    <>
      <Head>
        <title>Liga de Padel Baradero | Jugadores</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Box as="main" p={4}>
        <PageLayout>
          {{
            header: (
              <TournamentsHeader
                navigateToCreateTournament={navigateToCreateTournament}
              />
            ),
            content: (
              <TournamentList
                navigateToTournamentDetails={navigateToTournamentDetails}
              />
            ),
          }}
        </PageLayout>
      </Box>
    </>
  );
}
