name: build
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
      - development

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.3.0"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Checkout
        if: ${{ failure() }}
        uses: actions/checkout@v3
