name: static-checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
      - development

permissions: read-all

jobs:
  static-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.3.0"
          cache: "npm"
      - run: npm ci
      - run: git fetch origin main
      - run: npm run lint
      - run: npm run prettier:ci
